/*USER_ME */

export const SESSION_REQUEST = 'SESSION_REQUEST'
export const SESSION_SUCCESS = 'SESSION_SUCCESS'
export const UNAUTHORIZED = 'UNAUTHORIZED'

/* LOGIN */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

/* FACEBOOK LOGIN */
export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';

/* TWITTER LOGIN */
export const TWITTER_LOGIN_REQUEST = 'TWITTER_LOGIN_REQUEST';
export const TWITTER_LOGIN_SUCCESS = 'TWITTER_LOGIN_SUCCESS';
export const TWITTER_LOGIN_FAIL = 'TWITTER_LOGIN_FAIL';


/* GMAIL LOGIN */
export const GMAIL_LOGIN_REQUEST = 'GMAIL_LOGIN_REQUEST';
export const GMAIL_LOGIN_SUCCESS = 'GMAIL_LOGIN_SUCCESS';
export const GMAIL_LOGIN_FAIL = 'GMAIL_LOGIN_FAIL';

/* SIGNUP */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

/* UPDATE LANGUAGE */
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';

/* GET ALL PARTIES */
export const GET_PARTIES_REQUEST = 'GET_PARTIES_REQUEST';
export const GET_PARTIES_SUCCESS = 'GET_PARTIES_SUCCESS';
export const GET_PARTIES_FAIL = 'GET_PARTIES_FAIL';
export const UPDATE_PARTIES = 'UPDATE_PARTIES';
export const DELETE_PARTIES = 'DELETE_PARTIES';

/* GET TODAY PARTIES */
export const GET_TODAY_PARTIES_REQUEST = 'GET_TODAY_PARTIES_REQUEST';
export const GET_TODAY_PARTIES_SUCCESS = 'GET_TODAY_PARTIES_SUCCESS';
export const GET_TODAY_PARTIES_FAIL = 'GET_TODAY_PARTIES_FAIL';
export const UPDATE_TODAY_PARTIES = 'UPDATE_TODAY_PARTIES';
export const DELETE_TODAY_PARTIES = 'DELETE_TODAY_PARTIES';

/* GET TOMORROW PARTIES */
export const GET_TOMORROW_PARTIES_REQUEST = 'GET_TOMORROW_PARTIES_REQUEST';
export const GET_TOMORROW_PARTIES_SUCCESS = 'GET_TOMORROW_PARTIES_SUCCESS';
export const GET_TOMORROW_PARTIES_FAIL = 'GET_TOMORROW_PARTIES_FAIL';
export const UPDATE_TOMORROW_PARTIES = 'UPDATE_TOMORROW_PARTIES';
export const DELETE_TOMORROW_PARTIES = 'DELETE_TOMORROW_PARTIES';

/* GET THIS WEEK PARTIES */
export const GET_THIS_WEEK_PARTIES_REQUEST = 'GET_THIS_WEEK_PARTIES_REQUEST';
export const GET_THIS_WEEK_PARTIES_SUCCESS = 'GET_THIS_WEEK_PARTIES_SUCCESS';
export const GET_THIS_WEEK_PARTIES_FAIL = 'GET_THIS_WEEK_PARTIES_FAIL';
export const UPDATE_THIS_WEEK_PARTIES = 'UPDATE_THIS_WEEK_PARTIES';
export const DELETE_THIS_WEEK_PARTIES = 'DELETE_THIS_WEEK_PARTIES';

/* GET FAVORITE PARTIES */
export const GET_FAVORITE_PARTIES_REQUEST = 'GET_FAVORITE_PARTIES_REQUEST';
export const GET_FAVORITE_PARTIES_SUCCESS = 'GET_FAVORITE_PARTIES_SUCCESS';
export const GET_FAVORITE_PARTIES_FAIL = 'GET_FAVORITE_PARTIES_FAIL';
export const UPDATE_FAVORITE_PARTIES = 'UPDATE_FAVORITE_PARTIES';
export const DELETE_FAVORITE_PARTIES = 'DELETE_FAVORITE_PARTIES';

// UPDATE LIKE OR UNLIKE OF ALL PARTY
export const UPDATE_LIKE_UNLIKE_ALL_PARTIES = 'UPDATE_LIKE_UNLIKE_ALL_PARTIES';

// UPDATE LIKE OR UNLIKE OF TODAY
export const UPDATE_LIKE_UNLIKE_TODAY_PARTIES = 'UPDATE_LIKE_UNLIKE_TODAY_PARTIES';

// UPDATE LIKE OR UNLIKE OF TOMORROW
export const UPDATE_LIKE_UNLIKE_TOMORROW_PARTIES = 'UPDATE_LIKE_UNLIKE_TOMORROW_PARTIES';

// UPDATE LIKE OR UNLIKE OF THIS WEEK
export const UPDATE_LIKE_UNLIKE_THIS_WEEK_PARTIES = 'UPDATE_LIKE_UNLIKE_THIS_WEEK_PARTIES';

// UPDATE LIKE OR UNLIKE OF CREATED
export const UPDATE_LIKE_UNLIKE_CREATED_PARTIES = 'UPDATE_LIKE_UNLIKE_CREATED_PARTIES';

// UPDATE LIKE OR UNLIKE OF ATTENDED
export const UPDATE_LIKE_UNLIKE_ATTENDED_PARTIES = 'UPDATE_LIKE_UNLIKE_ATTENDED_PARTIES';

// UPDATE LIKE OR UNLIKE OF PENDING
export const UPDATE_LIKE_UNLIKE_PENDING_PARTIES = 'UPDATE_LIKE_UNLIKE_PENDING_PARTIES';

// UPDATE ADD OR REMOVE FAVORITE 
export const UPDATE_ADD_OR_REMOVE_FAVORITE = 'UPDATE_ADD_OR_REMOVE_FAVORITE';



/* GET CREATED PARTIES */
export const GET_CREATED_PARTIES_REQUEST = 'GET_CREATED_PARTIES_REQUEST';
export const GET_CREATED_PARTIES_SUCCESS = 'GET_CREATED_PARTIES_SUCCESS';
export const GET_CREATED_PARTIES_FAIL = 'GET_CREATED_PARTIES_FAIL';
export const UPDATE_CREATED_PARTIES = 'UPDATE_CREATED_PARTIES';
export const DELETE_CREATED_PARTIES = 'DELETE_CREATED_PARTIES';

/* GET ATTEDNING PARTIES */
export const GET_ATTENDING_PARTIES_REQUEST = 'GET_ATTENDING_PARTIES_REQUEST';
export const GET_ATTENDING_PARTIES_SUCCESS = 'GET_ATTENDING_PARTIES_SUCCESS';
export const GET_ATTENDING_PARTIES_FAIL = 'GET_ATTENDING_PARTIES_FAIL';
export const DELETE_ATTENDING_PARTIES = 'DELETE_ATTENDING_PARTIES';
export const UPDATE_ATTENDING_PARTIES = 'UPDATE_ATTENDING_PARTIES';

/* GET  PENDING PARTIES */
export const GET_PENDING_PARTIES_REQUEST = 'GET_PENDING_PARTIES_REQUEST';
export const GET_PENDING_PARTIES_SUCCESS = 'GET_PENDING_PARTIES_SUCCESS';
export const GET_PENDING_PARTIES_FAIL = 'GET_PENDING_PARTIES_FAIL';
export const DELETE_PENDING_PARTIES = 'DELETE_PENDING_PARTIES';
export const UPDATE_PENDING_PARTIES = 'UPDATE_PENDING_PARTIES';

/* GET AVAILIBILITIES */
export const GET_AVAILIBILITIES_REQUEST = 'GET_AVAILIBILITIES_REQUEST';
export const GET_AVAILIBILITIES_SUCCESS = 'GET_AVAILIBILITIES_SUCCESS';
export const GET_AVAILIBILITIES_FAIL = 'GET_AVAILIBILITIES_FAIL';

// EMPTY ALL PARTIES
export const EMPTY_ALL_PARTIES = 'EMPTY_ALL_PARTIES';

/* POST AVAILIBILITIES */
export const POST_AVAILIBILITIES_REQUEST = 'POST_AVAILIBILITIES_REQUEST';
export const POST_AVAILIBILITIES_SUCCESS = 'POST_AVAILIBILITIES_SUCCESS';
export const POST_AVAILIBILITIES_FAIL = 'POST_AVAILIBILITIES_FAIL';

/* UPDATE AVAILIBILITIES */
export const UPDATE_AVAILIBILITIES_REQUEST = 'UPDATE_AVAILIBILITIES_REQUEST';
export const UPDATE_AVAILIBILITIES_SUCCESS = 'UPDATE_AVAILIBILITIES_SUCCESS';
export const UPDATE_AVAILIBILITIES_FAIL = 'UPDATE_AVAILIBILITIES_FAIL';

export const REMOVE_AVAILIBILITIES_SUCCESS = 'REMOVE_AVAILIBILITIES_SUCCESS';



/* CREATE EVENT */
export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';

/* UPDATE EVENT */
export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';

/* DELETE EVENT */
export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';

/* UPDATE PROFILE */
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

/* LIKE EVENT */
export const LIKE_EVENT_REQUEST = 'LIKE_EVENT_REQUEST';
export const LIKE_EVENT_SUCCESS = 'LIKE_EVENT_SUCCESS';
export const LIKE_EVENT_FAIL = 'LIKE_EVENT_FAIL';

/* NOTIFICATIONS */
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const EMPTY_NOTIFICATIONS = 'EMPTY_NOTIFICATIONS';
export const GET_TOTAL_NOTIFICATIONS = 'GET_TOTAL_NOTIFICATIONS';

/* LOGOUT */
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

/* FORGET PASSOWRD */
export const FORGET_PASSOWRD_REQUEST = 'FORGET_PASSOWRD_REQUEST';
export const FORGET_PASSOWRD_SUCCESS = 'FORGET_PASSOWRD_SUCCESS';
export const FORGET_PASSOWRD_FAIL = 'FORGET_PASSOWRD_FAIL';

/* SIDEBAR */
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

/* LOADER */
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

/* SET NOTIFICATION ID */
export const SET_PUSH_NOTIFICATION_ID_SUCCESS = 'SET_PUSH_NOTIFICATION_ID_SUCCESS';
export const SET_PUSH_NOTIFICATION_ID_FAIL = 'SET_PUSH_NOTIFICATION_ID_SUCCESS';


export const EVENT_CHECK_IN_SUCCESS = 'EVENT_CHECK_IN_SUCCESS'

export const UPDATE_CREATED_EVENT = 'UPDATE_CREATED_EVENT' 

